### ISSUE TITLE
Serious security threat 

### ISSUE THREAD

**Issue by RohitChattopadhyay** [kishanhitk/jumsRebootFlutter#1]
https://github.com/kishanhitk/jumsRebootFlutter/blob/5a375228acb8d4f0cdc24cd21df80c40ee670c09/lib/services/networking.dart#L30
https://github.com/kishanhitk/jumsRebootFlutter/blob/5a375228acb8d4f0cdc24cd21df80c40ee670c09/lib/services/networking.dart#L36
What is the need of storing the user password in your DB? 
I think you are using it to simulate login to JUMS website programatically.
You have printed the password and username at several place, everywhere its unencrpyted.
I have serious concerns with the way you are handling user password. 

Apart from that you are scraping the site which is not legal
You should inform existing users to change their passwords and stop the app unless you encrypt it properly, which I think will be tough as you wont be able to decrypt it for sending to JUMS site.

**Comment by kishanhitk** [comment]
I think there is a misunderstanding from your side. I am not storing any info in any database except the user's device. Please have a look at saveToDb method. This method only saves this information in sharedPreference on their device.

class Database {
  void saveToDb(User user, String uname, String pass) async {
    final String encodedData = SemButtons.encodeButtons(user.buttons);
    SharedPreferences prefs = await SharedPreferences.getInstance();
    prefs.setString('uname', uname);
    prefs.setString('pass', pass);
    prefs.setString('buttons', encodedData);
    prefs.setString('name', user.name);
    prefs.setString('course', user.course);
    prefs.setString('imgUrl', user.imgUrl);
  }
}

**Comment by RohitChattopadhyay** [comment]
> I think there is a misunderstanding from your side. I am not storing any info in any database except the user's device. Please have a look at saveToDb method. This method only saves this information in sharedPreference on their device.
> 
> class Database {
> void saveToDb(User user, String uname, String pass) async {
> final String encodedData = SemButtons.encodeButtons(user.buttons);
> SharedPreferences prefs = await SharedPreferences.getInstance();
> prefs.setString('uname', uname);
> prefs.setString('pass', pass);
> prefs.setString('buttons', encodedData);
> prefs.setString('name', user.name);
> prefs.setString('course', user.course);
> prefs.setString('imgUrl', user.imgUrl);
> }
> }

Yup, thats okay i guess
I was asking about how you are handling in heroku, is your Express code public?
